name: CI workflow

on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with: { java-version: 11 }

      - name: Run Detekt
        run: |
          ./gradlew detekt

      - name: Run Ktlint
        run: |
          ./gradlew ktlintCheck

      - name: Run Unit tests
        run: |
          ./gradlew :nfc:testDebugUnitTest
