name: CI workflow

on: 
  push: 
    paths-ignore:
      - '**.md'
    branches: [ gh-actions-workflow ] 
  pull_request:  
    paths-ignore:
      - '**.md'
    branches: [ gh-actions-workflow ]

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with: {java-version: 1.8}

      - name: Run tests and build release artifacts
        run: |
          ./gradlew test
